name: Docker - 7.4

on:
  push:
    paths:
      - .github/workflows/7.4.yaml
      - '7.4/**'

jobs:
  build:
    name: Build 1.10
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: '7.4'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/webserver:7.4-latest
          push: true
